### ISSUE TITLE
Vagrant 1.9.3 up fails

### ISSUE THREAD

**Issue by grizzer** [rapid7/metasploitable3#106]
## Issue Description
'vagrant up' fails trying to initialize port forwarding because Vagrant 1.9.3 adds a new Vargrantfile variable for mapped ports, "host_ip"
https://github.com/mitchellh/vagrant/issues/8395

The error message is
"is_port_open.rb:21: in 'initialize': The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 3389 (Errno::EADDRNOTAVAIL)

According to the issue on the Vagrant project, the fix is to add a value for host_ip.
Ex:
config.vm.network "forwarded_port", guest: 22, host: 1022, host_ip: "127.0.0.1", id: 'ssh'

I tested adding this to vagrantfile-windows_2008_r2.template _before_ running the PS1 to build the box, and it works. I don't know if adding that would have a negative effect on vagrant < 1.9.3 though.

**Comment by jbarnett-r7** [comment]
Looks like this was fixed on the [Vagrant end](https://github.com/mitchellh/vagrant/pull/8399) but hasn't been released yet. As a workaround you can downgrade to 1.9.2, or wait for them to push out the fix in a release.

**Comment by 0xW1sKy** [comment]
for anyone else having isues with this:
More info from the vagrant thread regarding this

according to the vagrant thread, its better to use "localhost" instead of "127.0.0.1"
apparently "localhost" is how you get it to work on all interfaces.
C:\Users\<your username>\.vagrant.d\boxes\metasploitable3\0\virtualbox
open "Vagrantfile" with a text editor.

adjust the following 2 lines:

config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", host_ip: "localhost", auto_correct: true
config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", host_ip: "localhost", auto_correct: true

**Comment by helmbold** [comment]
It would be helpful to mention the requirement of the `host_ip` in the documentation. For example [here](https://www.vagrantup.com/docs/networking/forwarded_ports.html).
