### ISSUE TITLE
Windows 2008 Installation

### ISSUE THREAD

**Issue by Secr3ts** [rapid7/metasploitable3#335]
## Issue Description
When launching the Vm (In Vmware) i can't install it because there is a error message who tell 
" Windows could not apply the unattend answer file's <DiskConfiguration> ,,
## Host System
* OS: Windows 10 (x64)
* Packer Version: 1.2.5
* Vagrant Version: 2.1.4
* VmWare Version: 14.0.0 build-6661328

## Screenshots
![capture d ecran 10](https://user-images.githubusercontent.com/42939294/44991231-b23a0400-af93-11e8-8070-bd11e7f56fe7.png)

**Comment by Secr3ts** [comment]
Ok can you close this issue now?
Thanks.

**Comment by pielgrzym** [comment]
Hi,

I've got exactly the same issue - how did you resolve it?

**Comment by Secr3ts** [comment]
I don't really know sry but what I did is re-starting from scratch and it worked

**Comment by pielgrzym** [comment]
No problem. Googling this error lead me to information that virtio disk drivers are probably not loaded for some reason and automated install can't partition the disk. When I changed the json template and added "disk_interface": "ide" to qemu setup the bug did not appear. Now this still sucks since ide disk driver performance is apalling and I don't know if there is any way to change it later to virtio, but we'll see and learn. 

Thanks anyway, since your bugreport lead me to this discovery ;)

**Comment by pielgrzym** [comment]
For lone travelers looking to **fix this problem the proper way**: my debian install was lacking p7zip-full package and `build.sh` could not unpack downloaded virtio drivers. Funny part is: there is a verbose message about this I somehow ignored multiple times. I only understood what happened after reading source code. Selective blindness, go figure.
