### ISSUE TITLE
Wrong variable name "7 of diamonds". Shoud be "7_of_diamonds"

### ISSUE THREAD

**Issue by azerhouani** [rapid7/metasploitable3#382]
## Issue Description

**But reported by Thomas Laurenson in his [tutorial](https://www.thomaslaurenson.com/blog/2018/07/03/metasploitable3-building-the-ubuntu-linux-version/).**

BUG FIX

This step is very important. When building Metasploitable3 for this tutorial, I found a bug in the configuration for one of the flags… specifically, the 7_of_diamonds flag. If the following bug fix is not implemented, your build will fail!

Open the flags.rb file, where the configuration for the system flags is performed.

`vim chef/cookbooks/metasploitable/recipes/flags.rb`

Locate line 38. Basically, we need to change one of the lines which have an error. The specific flag is the 7_of_diamonds, and the docker image that is built for this flag refers to an incorrect name. In the code, it is specified as 7 of diamonds, while it should be 7_of_diamonds. The original code is listed below:
```
bash 'build docker image for 7 of diamonds' do
  code <<-EOH
    cd /opt/docker
    docker build -t "7_of_diamonds" .
    docker run -dit --restart always --name 7_of_diamonds 7_of_diamonds
  EOH
end
```
Make sure to change the code to the following listing (note the added underscore character to the first line!):
```
bash 'build docker image for 7_of_diamonds' do
  code <<-EOH
    cd /opt/docker
    docker build -t "7_of_diamonds" .
    docker run -dit --restart always --name 7_of_diamonds 7_of_diamonds
  EOH
end
```

## Host System
* OS: Ubuntu 18.04
* Packer Version: 1.3.5
* Vagrant Version: 2.2.4
* VirtualBox Version: 6.0.4

## Command Output
Everything was said at the beginning.

**Comment by jmartin-r7** [comment]
This is not actually required.  According to [chef documentation](https://docs.chef.io/resource_bash.html)  the string `'build docker image for 7 of diamonds'` is simply a name, since the name does not need to be referenced to execute the recipe it does not need to match the name of the docker image.

Just encase, I ran a local build of `master` for the `ub1404` vm and verified the docker image for `7_of_diamonds` is installed and started without any change.
