### ISSUE TITLE
SOLVED:  package build creates windows2008 image with no NICs

### ISSUE THREAD

**Issue by obitori** [rapid7/metasploitable3#426]
## Issue Description
I seem to be running into cascading driver problems with the windows version of Metasploitable 3.  

# First Problem (solved)

Originally, it would hang during installation with the following error:
> "windows could not apply unattend answer file's <DiskConfiguration> setting"

I implemented @pyhoff's solution described [here.](https://github.com/rapid7/metasploitable3/issues/420)  That solved the unattend file problem, but packer proceeded to build an image with no NICs installed.  This, not surprisingly, caused the install script to stall at the SSH login.  (No NIC means no network connection means no SSH service to log into.)  

# New Problem
I am trying to install the missing NICs on the Windows guest.
  
I took a look at the metasploitable3/packer/scripts/virtio-win-drivers.sh script and the download URL that it references (see below) to pull down the virtio drivers. The website [fedorapeople](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/) contains a long list of virtio drivers for windows and it appears that the format has changed over time. (Compare the contents of the iso in a 2016 version versus a 2019 version.)

So, I tried hardcoding a reference to a couple 2016 versions of the vfd file in the virtio-win-drivers.sh script. Here is my script after the edit:

# URI for downloading the latest WHQL'd Virtio drivers
virtio_uri="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.126-2/virtio-win-0.1.126_amd64.vfd"

I should add that because Metasploitable3 was released in November 2016, I figured the 126-2 version listed above (which was uploaded in September 2016) would likely have been the version that the Metasploitable3 developers built against. But, still no NIC, no joy! :(

I see that the Autounattend.xml and the contents of the win-virtio iso put in the resources directory are available on the Windows2008 guest via the floppy drive (A:). Question is what do I need to configure on the kvm side to get a NIC and then I can install the correct driver via the A: drive. Anyway, that's what I am thinking.  

Virt-manager does not see this qemu guest because of how it is built with Packer and Vagrant (I assume).  If it did, I could just add the NIC thru virt-manager and add the drivers inside the guest.  I could do the same with the xml template, but virsh doesn't see it either.

## Host System
* OS:  Ubuntu 19.10
* Packer Version:  1.3.4
* Vagrant Version:  2.2.6
* VirtualBox Version:  qemu-system-x86_64 [QEMU emulator version 4.0.0 (Debian 1:4.0+dfsg-0ubuntu9)]

**Comment by pyhoff** [comment]
I left a clue, look at the repo if you navigate into the drivers section for Win2012 and 2016 images you will find what the you should be doing.
Guess you did not see it this way. You have this error because your image does not have the required NIC drivers, packer can't complete the build since it can't connect to run required files.
For the initial build packer provides you a virtual floppy file, it builds this from the contents of the resources/drivers/ l issue is it's limited to 1.44 MB, so only include the required files.

I did it by creating 2 folders for these viostor and netkvm Copy only the files listed in the images below, do not add anything else.
VIOSTOR folder should only contain:
image
NETKVM folder should only contain:
image
NOTE
Once the packer build is complete you may also have to add the boxes to vagrant, so read up on how to do this with vagrant box add --name <file name> path/to/file
Also read up on how to modify the Vagrantfile on the root of the metasplotable folder so you can spin up the VMs using the vagrant up <imagename> where image name is either metasploitable3-ub1404 or metasploitable3-win2k8.

A lot of manual work with this one if using QEMU, the authors have mostly focused on Oracle Virtual box and VMWARE. Which is OK, may not be as smooth but at least makes you learn new stuff.
NEVER STOP LEARNING.
PEACE

**Comment by pyhoff** [comment]
please see comment https://github.com/rapid7/metasploitable3/issues/420#issuecomment-552150164

**Comment by obitori** [comment]
Your clue was quite helpful.  I was looking at how the A: drive contents were assembled when I got your last message.  Moved the right files (the ones you listed) into place inside of metasploitable3/resources/drivers/virtio/amd64/Win2008 and edited txtsetup.oem to look for them per your earlier post.  I see an active NIC...BAM...It worked.

Thanks @pyhoff!!!

Thanks for the tips on follow-on issues.  Will definitely take a look.  Meanwhile, I'll close this out.
