### ISSUE TITLE
Deprecated configuration key error

### ISSUE THREAD

**Issue by FerretEsq** [rapid7/metasploitable3#467]
## Issue Description
Upon trying to build the machine, I encounter the following error: 
"1 error occurred:                                                                                                               * Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`                                   against your template to update your template to be compatible with the current                                         version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more                                              detail."

I've already run the packer fix command and it didn't do anything.
Please help ;_;

## Host System
* OS: Windows 10 home 64bit
* Packer Version:1.6.0
* Vagrant Version:2.2.9
* VirtualBox Version:6.0.22

## Command Output
Github gist of the error:
https://gist.github.com/FerretEsq/d91b339b137584879d8347c8905218d3

**Comment by zackage** [comment]
I figured out how to solve this problem on my local machine. Here are the steps I took.

1. Rather than simply call packer fix on the ubuntu1404 json file, you need to redirect the output to another file, meaning having additional "> Newfilename" at the end of the command.

2. I copied all the lines in Newfilename, except for the several empty lines at the end of the file, into another "actual new ubuntu .json" file and follow the rest of the installation instructions. So the packer build --only=virtualbox-iso NewUbuntu.json command in my case.

3. If you receive another error telling you a virtual machine folder already exists somewhere, you'll need to remove the existing metasploitable3 folder in your virtual machine folder. In my case it's a metasploitable3 folder inside the [myusername]/Virtual Box VMs/ folder. Once metasploitable3 folder is removed, the rest of the installation instructions should run smoothly.

Hope this helps

**Comment by FerretEsq** [comment]
It did! Beautiful, thank you very much for the help
