### ISSUE TITLE
vagrant up give error: undefined local variable or method 'win2k8'

### ISSUE THREAD

**Issue by RobertoD91** [rapid7/metasploitable3#492]
## Issue Description
after `vagrant up` i get this error `Message: undefined local variable or method 'win2k8'`

## Host System
* OS: macOS 10.15.7
* Packer Version:1.6.4
* Vagrant Version:2.2.10
* VirtualBox Version: 6.1.14 r140239

## Command Output
```
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/xxx/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0.1.0-weekly/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'
```

**Comment by dgsaltarin** [comment]
I'm having the same issue

**Comment by jele84** [comment]
Having the same issue also

==> win2k8: Successfully added box 'rapid7/metasploitable3-win2k8' (v0.1.0-weekly) for 'virtualbox'!
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/user/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0.1.0-weekly/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'

**Comment by democaf** [comment]
I am also facing the same issue

PS C:\Users\**\**\GitHub\metasploitable3> vagrant box add.\windows_2008_r2_virtualbox_0.1.0.box --name=metasploitable3
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: C:/**/**/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'
PS C:\Users\**\**\GitHub\metasploitable3>

**Comment by luxbyte8** [comment]
I am not sure if this is the proper way to fix it but it seems to have worked for me.
Open the vagrantfile that is causing the error. Look for where it says "win2k8"
There was only one place where it uses win2k8 in the file:
**win2k8.vm.provider "libvirt" do |v|**
Change it to:
**config.vm.provider "libvirt" do |v|**
Then run "vagrant up win2k8" again and it should work.

**Comment by dgsaltarin** [comment]
> 
> 
> I am not sure if this is the proper way to fix it but it seems to have worked for me.
> Open the vagrantfile that is causing the error. Look for where it says "win2k8"
> There was only one place where it uses win2k8 in the file:
> **win2k8.vm.provider "libvirt" do |v|**
> Change it to:
> **config.vm.provider "libvirt" do |v|**
> Then run "vagrant up win2k8" again and it should work.

I confirm that this solution worked for me, thank you so much.

**Comment by democaf** [comment]
> > I am not sure if this is the proper way to fix it but it seems to have worked for me.
> > Open the vagrantfile that is causing the error. Look for where it says "win2k8"
> > There was only one place where it uses win2k8 in the file:
> > **win2k8.vm.provider "libvirt" do |v|**
> > Change it to:
> > **config.vm.provider "libvirt" do |v|**
> > Then run "vagrant up win2k8" again and it should work.
> 
> I confirm that this solution worked for me, thank you so much.

It worked

**Comment by apwellington** [comment]
this solution worked for me, thank you.

**Comment by phs635912** [comment]
> > > I am not sure if this is the proper way to fix it but it seems to have worked for me.
> > > Open the vagrantfile that is causing the error. Look for where it says "win2k8"
> > > There was only one place where it uses win2k8 in the file:
> > > **win2k8.vm.provider "libvirt" do |v|**
> > > Change it to:
> > > **config.vm.provider "libvirt" do |v|**
> > > Then run "vagrant up win2k8" again and it should work.
> > 
> > 
> > I confirm that this solution worked for me, thank you so much.
> 
> It worked

It doesn`t still worked,and export info :
![image](https://user-images.githubusercontent.com/59989419/96073071-3e8bb480-0ed8-11eb-9014-5f7d9d7c6d0b.png)

**Comment by phs635912** [comment]
> > > I am not sure if this is the proper way to fix it but it seems to have worked for me.
> > > Open the vagrantfile that is causing the error. Look for where it says "win2k8"
> > > There was only one place where it uses win2k8 in the file:
> > > **win2k8.vm.provider "libvirt" do |v|**
> > > Change it to:
> > > **config.vm.provider "libvirt" do |v|**
> > > Then run "vagrant up win2k8" again and it should work.
> > 
> > 
> > I confirm that this solution worked for me, thank you so much.
> 
> It worked
I try to modify it,It doesn`t still worked.

The machine with the name 'win2k8' was not found configured for
this Vagrant environment.

**Comment by phs635912** [comment]
I resolved the issue,I replaced the Vagrantfile in the directory Metasploitable3-master with the Vagrantfile in the directory Rapid7-vagrantslash-metasploitable3-win2k8/0.1.0-weekly/Virtualbox

**Comment by sharkol** [comment]
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/xxx/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0.1.0-weekly/virtualbox/Vagrantfile
Line number: 0
Message: undefined local variable or method `win2k8'


environment
macox 10.15.7

**Comment by deanbushmiller** [comment]
+1 for sharkol
ONLY difference is macox 10.15.6

> Vagrant failed to initialize at a very early stage:
> 
> There was an error loading a Vagrantfile. The file being loaded
> and the error message are shown below. This is usually caused by
> an invalid or undefined variable.
> 
> Path: /Users/xxx/.vagrant.d/boxes/rapid7-VAGRANTSLASH-metasploitable3-win2k8/0.1.0-weekly/virtualbox/Vagrantfile
> Line number: 0
> Message: undefined local variable or method `win2k8'
> 
> environment
> macox 10.15.7

**Comment by jmartin-r7** [comment]
A new image has been pushed to vagrantcloud for anyone having this issue when using the [Quick Start](https://github.com/rapid7/metasploitable3#quick-start) instructions for vmware or virtualbox.

Any existing local vagrant box will need to be deleted to pull the new images.
