### ISSUE TITLE
Separate vagrant from VM after build and make metasploitable 3 

### ISSUE THREAD

**Issue by patronplatform** [rapid7/metasploitable3#536]
hi I was setting up Metasploitable 3 with PowerShell and build.ps1 file 
I just run it without " vagrant up " command 
now I need to Make Virtual box environment but now when I close power shell virtual machine is deleting ..
![image](https://user-images.githubusercontent.com/45009415/120923145-45bf3700-c6e2-11eb-8190-0da253e0976b.png)
how can I do ?

## Host System
* OS: Win 10
* Packer Version:  1.5.6
* Vagrant Version: 2.2.16
* VirtualBox Version: 6.1

**Comment by jmartin-r7** [comment]
When using `build.ps1` the project is created a virtual machine from scratch when the build completes it would import the finished box image into vagrant. 

`packer` deletes a build when a failure occurs.  If you want to build locally, something in the output would have provided details about the failure.

When simply calling `vagrant up` the box image from vagrant cloud will be downloaded instead of building locally.

Please try again.
