### ISSUE TITLE
Cannot get elasticsearch-service-x64 to run 

### ISSUE THREAD

**Issue by azzarin** [rapid7/metasploitable3#57]
Cannot get elasticsearch-service-x64. 
Cannot see it being installed either. 

Have i done something wrong? does the build fail on some of the services ? 

Thank you.

**Comment by jbarnett-r7** [comment]
I just built with the latest code (`git pull` and `vagrant up`) and the elasticsearch service is present and running. Can you please try running `vagrant destroy` and then `vagrant up` again to see if it installs properly this time? If not, can you please copy the output from `vagrant up` and post it here?

**Comment by azzarin** [comment]
I did as you said. It did work the 3rd time. It looks totaly different now. And the services is running. Thank you for the help.

**Comment by mbauer588** [comment]
Hallo!

I have the same problem... I try to create it 2 times and i miss multiple services - e.g. elasticsearch, ftp, iis, etc.

My nmap-scan looks like this:

nmap -O -sS -sV -sC -p 1-65535 -oA nmap/win2008 --stylesheet=nmap.xsl --open --reason 192.168.1.104

Starting Nmap 7.40 ( https://nmap.org ) at 2017-04-27 13:44 CEST
Nmap scan report for 192.168.1.104
Host is up, received arp-response (0.00049s latency).
Not shown: 65528 filtered ports
Some closed ports may be reported as filtered due to --defeat-rst-ratelimit
Reason: 65528 no-responses
PORT      STATE SERVICE       REASON          VERSION
22/tcp    open  ssh           syn-ack ttl 128 OpenSSH 7.1 (protocol 2.0)
| ssh-hostkey: 
|   2048 dc:17:a5:fc:2e:19:13:62:0e:5a:2f:df:9e:5c:64:72 (RSA)
|_  521 52:c4:78:6e:7f:fe:5a:bc:d5:16:c7:cb:ff:d6:56:ed (ECDSA)
135/tcp   open  msrpc         syn-ack ttl 128 Microsoft Windows RPC
445/tcp   open  microsoft-ds  syn-ack ttl 128 Windows Server 2008 R2 Standard 7601 Service Pack 1 microsoft-ds
3389/tcp  open  ms-wbt-server syn-ack ttl 128 Microsoft Terminal Service
| ssl-cert: Subject: commonName=metasploitable3
| Not valid before: 2017-04-25T23:40:13
|_Not valid after:  2017-10-25T23:40:13
|_ssl-date: 2017-04-27T11:47:49+00:00; +2s from scanner time.
5985/tcp  open  http          syn-ack ttl 128 Microsoft HTTPAPI httpd 2.0 (SSDP/UPnP)
|_http-server-header: Microsoft-HTTPAPI/2.0
|_http-title: Not Found
49153/tcp open  msrpc         syn-ack ttl 128 Microsoft Windows RPC
49154/tcp open  msrpc         syn-ack ttl 128 Microsoft Windows RPC
MAC Address: 08:00:27:77:66:19 (Oracle VirtualBox virtual NIC)
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
Aggressive OS guesses: Microsoft Windows Server 2008 or 2008 Beta 3 (91%), Microsoft Windows Server 2008 (90%), Microsoft Windows Server 2008 SP1 (87%), HP-UX B.11.31 (87%), Isilon IQ 200 NAS device (87%), VMware ESXi 4.0 (87%), FreeBSD 6.2-RELEASE (86%), FreeBSD 5.5-RELEASE (86%), Microsoft Windows 7 SP1 (86%), m0nowall 1.3b16 firewall (FreeBSD 6.3-RELEASE) (85%)
No exact OS matches for host (test conditions non-ideal).
Network Distance: 1 hop
Service Info: OSs: Windows, Windows Server 2008 R2 - 2012; CPE: cpe:/o:microsoft:windows

Host script results:
|_clock-skew: mean: 1s, deviation: 0s, median: 1s
| smb-os-discovery: 
|   OS: Windows Server 2008 R2 Standard 7601 Service Pack 1 (Windows Server 2008 R2 Standard 6.1)
|   OS CPE: cpe:/o:microsoft:windows_server_2008::sp1
|   Computer name: metasploitable3
|   NetBIOS computer name: METASPLOITABLE3\x00
|   Workgroup: WORKGROUP\x00
|_  System time: 2017-04-27T04:47:52-07:00
| smb-security-mode: 
|   account_used: guest
|   authentication_level: user
|   challenge_response: supported
|_  message_signing: disabled (dangerous, but default)
|_smbv2-enabled: Server supports SMBv2 protocol

OS and Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 208.95 seconds
